# Welcome to Jekyll!
title: Asociación La Buena Leche
email: mail@example.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://labuenaleche.org" # the base hostname & protocol for your site, e.g. http://example.com
gtag: UA-XXXXXXXX-X
iban: ESXX XXXX XXXX XXXX XXXX XXXX

# Social network and other links
social:
  twitter: asociacionlbl
  facebook: AsociacionLaBuenaLeche
  blog: //compartiendocrianza.blogspot.com.es

markdown: kramdown
plugins:
  - jekyll-assets
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
